sudo: false
language: node_js
cache:
  directories:
    - node_modules
node_js:
  - "4.2"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
notifications:
  email: false
before_script:
  - npm prune
script:
  - npm run lint
  - npm run test
